baseURL = "https://rd-ulfri.netlify.com/"
languageCode = "en-us"
title = "R&D @ UL FRI"
theme = "minimal"
disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "University of Ljubljana, Faculty of Computer and Information Science"
    description = "Research and development at University of Ljubljana,  \nFaculty of Computer and Information Science"
    githubUsername = "#ul-fri"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    copyright = "&copy; {year} UL FRI. All rights reserved. Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal). Shipped by [netlify](https://www.netlify.com)."

[[menu.main]]
    url = "/"
    name = "About"
    weight = 1

[[menu.main]]
    url = "/researchers/"
    name = "Researchers"
    weight = 2

[[menu.main]]
    url = "/publications/"
    name = "Publications"
    weight = 3

[[menu.main]]
    url = "/doctoral-graduates/"
    name = "Doctoral graduates"
    weight = 4

[[menu.main]]
    url = "/doctoral-mentors"
    name = "Doctoral mentors"
    weight = 5

[[menu.main]]
    url = "/software-project/"
    name = "Software projects"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/ul-fri/"
    name = "fab fa-github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/ul_fri/"
    name = "fab fa-twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/school/ulfri"
    name = "fab fa-linkedin"
    weight = 3
